### ISSUE TITLE
Add command-line filter for an specific version

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/pypickup#36]
It would be a good idea to add a command-line filter so we can install on pypickup a particular version from a library.
The syntax could be something like `pypickup add numpy==1.24.3` and then the version 1.24.3 from `numpy` would get installed in `numpy`. This would allow a more user friendly interface and we wouldn't need to keep changing the filter yaml.

**Comment by HerManNav** [comment]
the commit [c1714a0](https://github.com/bsc-quantic/pypickup/commit/c1714a05c9e307bbe4bb7a55cee20ad8f30b1ba1) should solve the issue.

I added support for version specification for all the commands (add, update, list and rm). 

@jofrevalles can you make some quick tests? i you miss some useful behaviour, just let me know.

**Comment by jofrevalles** [comment]
@HerManNav Perfect! I have tried it and the command works very well.

Nevertheless, I would like to bring a potential issue to your attention. Currently, when we execute the command `pypickup add numpy==1.19.4` when we already have some other version installed, it complains since we already have `numpy` downloaded, and we have to do `pypickup update numpy==1.19.4` instead. From my perspective, it would seem more intuitive if the `add` command could function as expected even when different versions of `numpy` are present, as long as the specified version, in this case `numpy==1.19.4`, is not already installed.

However, I recognize that this could be a matter of personal preference and both implementations can be considered valid, depending on one's perspective. It is merely a suggestion for further enhancing the user experience, if you find it worthwhile.

Thank you for your attention
